{"name": "Нельзя авторизоваться, если login - не верный", "status": "passed", "description": "Negative test. Answer: 404 Bad Request \"message\":  \"Учетная запись не найдена\"", "attachments": [{"name": "stdout", "source": "102ac424-0fd4-46da-9b20-49fd4b0ef40a-attachment.txt", "type": "text/plain"}], "start": 1723147925682, "stop": 1723147925790, "uuid": "f6807594-5157-408b-9d2f-29b38c2671f6", "historyId": "bd3b59b85b935d736d05f0eb215f62ff", "testCaseId": "bd3b59b85b935d736d05f0eb215f62ff", "fullName": "test_login_courier.TestLoginCourier#test_4_authorization_courier_wrong_login", "labels": [{"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-KL5MP4V8"}, {"name": "thread", "value": "1220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_courier"}]}